DROP TABLE IF EXISTS user;
CREATE TABLE user(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	user_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'userName',
	password VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'password',
	birthday DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'birthday',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS log;
CREATE TABLE log(
	id VARCHAR (50) NOT NULL AUTO_INCREMENT COMMENT '主键',
	type VARCHAR (50) NOT NULL DEFAULT '' COMMENT '日志类型',
	title VARCHAR (50) NOT NULL DEFAULT '' COMMENT '日志标题',
	remote_addr VARCHAR (50) NOT NULL DEFAULT '' COMMENT '请求地址',
	request_uri VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'URI',
	method VARCHAR (50) NOT NULL DEFAULT '' COMMENT '请求方式',
	params VARCHAR (50) NOT NULL DEFAULT '' COMMENT '提交参数',
	exception VARCHAR (50) NOT NULL DEFAULT '' COMMENT '异常',
	operate_date DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '开始时间',
	timeout VARCHAR (50) NOT NULL DEFAULT '' COMMENT '结束时间',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;